"""Fix foreign key relationship between ChatbotUserModel and ChatbotChatModel

Revision ID: 20cf9b2fc666
Revises: 2263a4f4d759
Create Date: 2024-08-13 13:38:38.602302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cf9b2fc666'
down_revision: Union[str, None] = '2263a4f4d759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatbot_interactions_user_id_fkey', 'chatbot_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_interactions', 'chatbot_users', ['user_id'], ['id'])
    op.drop_column('chatbot_users', 'preferences')
    op.drop_column('chatbot_users', 'profile_picture')
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'profile_picture')
    op.add_column('chatbot_users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chatbot_users', sa.Column('preferences', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbot_interactions', type_='foreignkey')
    op.create_foreign_key('chatbot_interactions_user_id_fkey', 'chatbot_interactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
