"""Added more relationships

Revision ID: 2263a4f4d759
Revises: 1a456341c027
Create Date: 2024-08-13 13:19:10.228763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2263a4f4d759'
down_revision: Union[str, None] = '1a456341c027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatbot_interactions_user_id_fkey', 'chatbot_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_interactions', 'users', ['user_id'], ['id'])
    
    # Add user_id and vendor_id columns to chatbot_users
    op.add_column('chatbot_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('chatbot_users', sa.Column('vendor_id', sa.Integer(), nullable=True))
    
    # Create foreign keys for chatbot_users
    op.create_foreign_key(None, 'chatbot_users', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'chatbot_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbot_users', type_='foreignkey')
    op.drop_constraint(None, 'chatbot_users', type_='foreignkey')
    op.drop_column('chatbot_users', 'vendor_id')
    op.drop_column('chatbot_users', 'user_id')
    
    op.drop_constraint(None, 'chatbot_interactions', type_='foreignkey')
    op.create_foreign_key('chatbot_interactions_user_id_fkey', 'chatbot_interactions', 'chatbot_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
