"""Added profile picture and prefrence

Revision ID: 72274fa576e2
Revises: 20cf9b2fc666
Create Date: 2024-08-13 14:47:09.559289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72274fa576e2'
down_revision: Union[str, None] = '20cf9b2fc666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('chatbot_users', sa.Column('preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_users', 'preferences')
    op.drop_column('chatbot_users', 'profile_picture')
    # ### end Alembic commands ###
