"""Added profile picture

Revision ID: 8f608b01c1de
Revises: 72274fa576e2
Create Date: 2024-08-13 21:09:33.063924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f608b01c1de'
down_revision: Union[str, None] = '72274fa576e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'hashed_password')
    op.drop_column('vendors', 'profile_picture')
    op.drop_column('vendors', 'rating')
    op.drop_column('vendors', 'description')
    # ### end Alembic commands ###
