"""Added ChatbotUserModel and changed ChatbotModel to ChatbotChatModel

Revision ID: ad2b6289f32f
Revises: d9b3fcc4db10
Create Date: 2024-08-13 11:29:26.054407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2b6289f32f'
down_revision: Union[str, None] = 'd9b3fcc4db10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('preferences', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_users_email'), 'chatbot_users', ['email'], unique=True)
    op.create_index(op.f('ix_chatbot_users_id'), 'chatbot_users', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_users_username'), 'chatbot_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_users_username'), table_name='chatbot_users')
    op.drop_index(op.f('ix_chatbot_users_id'), table_name='chatbot_users')
    op.drop_index(op.f('ix_chatbot_users_email'), table_name='chatbot_users')
    op.drop_table('chatbot_users')
    # ### end Alembic commands ###
