"""Added phone number and full_name

Revision ID: b1328509605a
Revises: fb43b431f348
Create Date: 2024-10-01 17:55:16.554270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1328509605a'
down_revision: Union[str, None] = 'fb43b431f348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('chatbot_users', sa.Column('phoneNumber', sa.String(length=15), nullable=True))
    op.alter_column('chatbot_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_chatbot_users_email', table_name='chatbot_users')
    op.drop_index('ix_chatbot_users_username', table_name='chatbot_users')
    op.create_unique_constraint(None, 'chatbot_users', ['phoneNumber'])
    op.create_unique_constraint(None, 'chatbot_users', ['email'])
    op.drop_column('chatbot_users', 'username')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=15), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['phoneNumber'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'full_name')
    op.add_column('chatbot_users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatbot_users', type_='unique')
    op.drop_constraint(None, 'chatbot_users', type_='unique')
    op.create_index('ix_chatbot_users_username', 'chatbot_users', ['username'], unique=True)
    op.create_index('ix_chatbot_users_email', 'chatbot_users', ['email'], unique=True)
    op.alter_column('chatbot_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chatbot_users', 'phoneNumber')
    op.drop_column('chatbot_users', 'full_name')
    # ### end Alembic commands ###
