"""Added prefrence

Revision ID: b143515b4f01
Revises: 8f608b01c1de
Create Date: 2024-08-13 21:19:35.303329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b143515b4f01'
down_revision: Union[str, None] = '8f608b01c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'preferences')
    # ### end Alembic commands ###
