"""Initial migration

Revision ID: d9b3fcc4db10
Revises: 
Create Date: 2024-08-12 11:10:33.357665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b3fcc4db10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('sellers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    op.create_index(op.f('ix_sellers_id'), 'sellers', ['id'], unique=False)
    op.create_index(op.f('ix_sellers_name'), 'sellers', ['name'], unique=True)

    op.create_table('chatbot_interactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('seller_id', sa.Integer(), nullable=True),
        sa.Column('interaction_type', sa.String(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chatbot_interactions_user_id'),
        sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name='fk_chatbot_interactions_seller_id'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_interactions_id'), 'chatbot_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_interactions_interaction_type'), 'chatbot_interactions', ['interaction_type'], unique=False)

    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_description', sa.String(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_orders_owner_id'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_description'), 'orders', ['order_description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_owner_id', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_description'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')

    op.drop_constraint('fk_chatbot_interactions_user_id', 'chatbot_interactions', type_='foreignkey')
    op.drop_constraint('fk_chatbot_interactions_seller_id', 'chatbot_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_chatbot_interactions_interaction_type'), table_name='chatbot_interactions')
    op.drop_index(op.f('ix_chatbot_interactions_id'), table_name='chatbot_interactions')
    op.drop_table('chatbot_interactions')

    op.drop_index(op.f('ix_sellers_name'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_id'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_table('sellers')

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
