"""Regenerate chatbot_users

Revision ID: fb43b431f348
Revises: b143515b4f01
Create Date: 2024-09-07 07:34:09.363478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb43b431f348'
down_revision: Union[str, None] = 'b143515b4f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('preferences', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_users_email'), 'chatbot_users', ['email'], unique=True)
    op.create_index(op.f('ix_chatbot_users_id'), 'chatbot_users', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_users_username'), 'chatbot_users', ['username'], unique=True)
    op.create_foreign_key(None, 'chatbot_interactions', 'chatbot_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbot_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_chatbot_users_username'), table_name='chatbot_users')
    op.drop_index(op.f('ix_chatbot_users_id'), table_name='chatbot_users')
    op.drop_index(op.f('ix_chatbot_users_email'), table_name='chatbot_users')
    op.drop_table('chatbot_users')
    # ### end Alembic commands ###
